# Generated by Django 4.2.4 on 2023-11-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCruzRoja', '0003_alter_donor__license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldonation',
            name='state',
            field=models.IntegerField(choices=[(1, 'Aprobada'), (2, 'En espera'), (0, 'Rechazada'), (4, 'Cancelada')], default=2),
        ),
    ]
