# Generated by Django 4.2.4 on 2023-11-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCruzRoja', '0006_remove_donor__license_remove_donor_civilstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rol',
            field=models.IntegerField(default=1),
        ),
    ]
