# Generated by Django 4.1.1 on 2023-11-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCruzRoja', '0007_employee_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='state',
            field=models.IntegerField(choices=[(1, 'Completa'), (2, 'Incompleta'), (3, 'Diferido'), (4, 'En proceso')], default=4),
        ),
    ]
